preload = ~/.dotfiles/wallpaper/keren.jpg
# wallpaper = eDP-1,~/Downloads/smiling-naruto-uzumaki-anime-desktop-wallpaper.jpg
# wallpaper = HDMI-A-1,~/Downloads/smiling-naruto-uzumaki-anime-desktop-wallpaper.jpg

wallpaper {
  monitor = HDMI-A-1
  path = ~/.dotfiles/wallpaper/keren.jpg
}

wallpaper {
  monitor = eDP-1
  path = ~/.dotfiles/wallpaper/keren.jpg
}


wallpaper {
  monitor = DP-1
  path = ~/.dotfiles/wallpaper/keren.jpg
}

splash = false
