preload = ~/.dotfiles/wallpaper/keren.jpg
# wallpaper = eDP-1,~/Downloads/smiling-naruto-uzumaki-anime-desktop-wallpaper.jpg
wallpaper = eDP-1,~/.dotfiles/wallpaper/keren.jpg
# wallpaper = HDMI-A-1,~/Downloads/smiling-naruto-uzumaki-anime-desktop-wallpaper.jpg
wallpaper = HDMI-A-1,~/.dotfiles/wallpaper/keren.jpg
wallpaper = DP-1,~/.dotfiles/wallpaper/keren.jpg
splash = false
