# In hyprland.conf
exec-once = hyprpaper &> /tmp/hyprpaper.log
exec-once = ~/.dotfiles/waybar/launch.sh
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = nm-applet &
exec-once = blueman-applet &
